session_name: 'dev'
windows:
- focus: 'true'
  layout: ba71,179x52,0,0{89x52,0,0,0,89x52,90,0[89x26,90,0,1,89x25,90,27,2]}
  options: {}
  panes:
  - focus: true
    shell_command:
    - nvim
  - pane
  window_name: dev
